# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('offset', models.FloatField(default=0)),
                ('stretching', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_index', models.PositiveIntegerField()),
                ('field_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FileFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_names', to='seaver_app.File')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntervalAnnotationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('stop', models.FloatField()),
                ('interval_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seaver_app.IntervalAnnotation')),
            ],
        ),
        migrations.CreateModel(
            name='PunctualAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PunctualAnnotationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.FloatField(default=0)),
                ('punctual_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seaver_app.PunctualAnnotation')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='punctualannotationevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctual_annotations', to='seaver_app.Workspace'),
        ),
        migrations.AddField(
            model_name='intervalannotationevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_annotations', to='seaver_app.Workspace'),
        ),
        migrations.AddField(
            model_name='filedata',
            name='field_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_datas', to='seaver_app.FileFieldName'),
        ),
        migrations.AddField(
            model_name='file',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='seaver_app.Workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='workspace',
            index_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='filefieldname',
            unique_together=set([('file', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='filedata',
            unique_together=set([('field_name', 'field_index')]),
        ),
        migrations.AlterIndexTogether(
            name='filedata',
            index_together=set([('field_name', 'field_index')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('workspace', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together=set([('workspace', 'name')]),
        ),
    ]
