# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seaver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together=set([('workspace', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='filedata',
            index_together=set([('file', 'field_name'), ('file', 'field_name', 'field_index')]),
        ),
        migrations.AlterIndexTogether(
            name='intervalannotationevent',
            index_together=set([('interval_annotation', 'index')]),
        ),
        migrations.AlterIndexTogether(
            name='punctualannotationevent',
            index_together=set([('punctual_annotation', 'index')]),
        ),
        migrations.AlterIndexTogether(
            name='workspace',
            index_together=set([('user', 'name')]),
        ),
    ]
