# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaver_app', '0002_auto_20170612_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='field_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='intervalannotationevent',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='punctualannotationevent',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
